### PR TITLE
Create basic SequenceDistanceGraph and DBG building based on Arda's code

### PR DESCRIPTION
**Pull request by TransGirlCodes**
@ardakdemir This is the SequenceDistanceGraph, based on your DeBruijn Graph code with some tweaks. Have a look at the methods it has and the dbg constructor. Let me know if you're happy with my edits to that algorithm.

### CODE REVIEW

**Comment by ardakdemir** [comment]
Everything looks fine for me!
I think there may arise some issues during edge addition with your dbg constructor if the reverse complement of a prefix/suffix of a kmer is equal to itself e.g ATA. Then adding it only to bw_nodes or fw_nodes will  skip some of the edges. I tried to explain this issue in my blog as well : https://ardakdemir.github.io/pages/gsoc.html 

Let me know if I am not clear or you think there is a mistake in my formulation.

**Comment by TransGirlCodes** [comment]
Hey @ardakdemir I've added an improvement to the DBG builder. This new function called `make_graph_from_kmerlist` has several improvements:
It can handle larger genomes, by using a sorted list of canonical kmers rather than a set which uses more memory, than the previous DBG stuff we've been working on.
It also builds unitigs straight away and adds them to the graph.

The ATAT ATA -> TAT problem you described also affects this algorithm too. The problem you were describing in your blog post is a small example of a more general problem called the circle problem, I'm glad you found it as I forgot about it. In the new function, this edge case takes the form of kmers in circles being excluded from the graph. To fix this we will need to take all the kmers that have not been used once unitig creation is done, and add those "circles" to the graph as units by choosing a random breakpoint.

But for now, until we squash this bug if the K used to build Kmers/Graph is large enough this edge case should be very rare, and we could add a test/warning message if the case does pop up!

**Comment by ardakdemir** [comment]
@BenJWard  thanks for the explanation.
I agree that the sorted list is a better implementation for representing the input kmers.
I think I am happy about the content :)

**Comment by TransGirlCodes** [comment]
Oops, hit the close button by accident.

**Pull request merged**
